package it.finanze.entrate.coopint.dboard.dpi.common.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

@Configuration
@ConfigurationProperties(prefix = "event")
public class EventNameProperties {
	// Aggiunti
	public static String ADD_CONTRIBUTE_TO_EFFECTIVE_DEST;
	public static String START_EXCEL_DAC7_NATIONAL;
	//

	public static String PROCESS_HISTORY;
	public static String UPDATE_STATUS;
	public static String DELETE_COMMUNICATION;
	public static String EXPIRED_FISCAL_YEAR;
	public static String UPDATE_FISCAL_YEAR;
	public static String BUILD_MESSAGE;
	public static String UPDATE_EFFECTIVE_DEST;
	public static String FINALIZE_COMMUNICATION;
	public static String ADD_EFFECTIVE_DEST;
	public static String REMOVE_EFFECTIVE_DEST;
	public static String LATE_COMMUNICATION;
	public static String FINISHED_EXPIRED_COMMUNICATIONS;
	public static String START_BUILDING_MESSAGES_EXPIRED_FY;
	public static String ACCEDED_COUNTRY;
	public static String RESTORED_COUNTRY;
	public static String BLOCKED_COUNTRY;

	public static String START_BUILDING_MESSAGES_SPECIFIC_COM;

	public static String START_BUILDING_MESSAGES_SPECIFIC_COUNTRY;

	public static String RETRANSMIT_MESSAGE;

	public static String REBUILD_MESSAGE;

	public static String DELETE_MESSAGE;

	public static String MESSAGE_VALIDATION;

	public static String NOTIFY_REMINDER_MESSAGES_READY_TO_SEND;

	public static String NOTIFY_REMINDER_STATUS_MESSAGE;

	public static String CLOSE_EXCHANGE_FOR_COUNTRY;

	public static String CHANGE_STATUS_PRENOTATO_INVIO;

	public static String MW_MSG_SENT;

	public static String CTS_UNPACKAGING_ERROR;

	public static String INCOMING_STATUS_MESSAGE_ERROR;

	public static String INCOMING_STATUSD_MESSAGE;

	public static String ALERT_MESSAGE;

	public static String RESEND_MESSAGE;

	public static String REWORK_STATUS_MESSAGE;

	public static String REMINDER_EMAIL;

	public static String INSERT_REPORT_ERROR;

	public static String UPDATE_REPORT_ERROR;

	public static String NOTIFY_REMINDER_NOT_CONCLUDED_NR;

	public static String UPDATE_NOTES;

	public static String REWORK_MESSAGE;

	public static String INCOMING_MESSAGE;

	public static String INCOMING_MESSAGE_BUSINESS_XML_NOT_VALID_AND_SEND_STATUS_MESSAGE;

	public static String INCOMING_MESSAGE_BUSINESS_WITH_STATUS_MESSAGE_SUSPENDED;

	public static String INCOMING_MESSAGE_BUSINESS_AND_SEND_STATUS_MESSAGE;

	public static String SEND_RESEND_STATUS_MESSAGE;

	public static String ALERT_STATUS_MESSAGE;

	public static String INCOMING_MESSAGE_BUSINESS_FAILED_DECRYPTION;

	public static String NOTIFY_REMINDER_NOT_CONCLUDED_RES;

	public static void setACCEDED_COUNTRY(String aCCEDED_COUNTRY) {
		ACCEDED_COUNTRY = aCCEDED_COUNTRY;
	}

	public static void setRESTORED_COUNTRY(String rESTORED_COUNTRY) {
		RESTORED_COUNTRY = rESTORED_COUNTRY;
	}

	public static void setBLOCKED_COUNTRY(String bLOCKED_COUNTRY) {
		BLOCKED_COUNTRY = bLOCKED_COUNTRY;
	}

	public static void setRETRANSMIT_MESSAGE(String rETRANSMIT_MESSAGE) {
		RETRANSMIT_MESSAGE = rETRANSMIT_MESSAGE;
	}

	public static void setREBUILD_MESSAGE(String rEBUILD_MESSAGE) {
		REBUILD_MESSAGE = rEBUILD_MESSAGE;
	}

	public static void setDELETE_MESSAGE(String dELETE_MESSAGE) {
		DELETE_MESSAGE = dELETE_MESSAGE;
	}

	public static void setMESSAGE_VALIDATION(String mESSAGE_VALIDATION) {
		MESSAGE_VALIDATION = mESSAGE_VALIDATION;
	}

	public static void setNOTIFY_REMINDER_MESSAGES_READY_TO_SEND(String nOTIFY_REMINDER_MESSAGES_READY_TO_SEND) {
		NOTIFY_REMINDER_MESSAGES_READY_TO_SEND = nOTIFY_REMINDER_MESSAGES_READY_TO_SEND;
	}

	public static void setNOTIFY_REMINDER_STATUS_MESSAGE(String nOTIFY_REMINDER_STATUS_MESSAGE) {
		NOTIFY_REMINDER_STATUS_MESSAGE = nOTIFY_REMINDER_STATUS_MESSAGE;
	}

	public static void setCLOSE_EXCHANGE_FOR_COUNTRY(String cLOSE_EXCHANGE_FOR_COUNTRY) {
		CLOSE_EXCHANGE_FOR_COUNTRY = cLOSE_EXCHANGE_FOR_COUNTRY;
	}

	public static void setCHANGE_STATUS_PRENOTATO_INVIO(String cHANGE_STATUS_PRENOTATO_INVIO) {
		CHANGE_STATUS_PRENOTATO_INVIO = cHANGE_STATUS_PRENOTATO_INVIO;
	}

	public static void setMW_MSG_SENT(String mW_MSG_SENT) {
		MW_MSG_SENT = mW_MSG_SENT;
	}

	public static void setCTS_UNPACKAGING_ERROR(String cTS_UNPACKAGING_ERROR) {
		CTS_UNPACKAGING_ERROR = cTS_UNPACKAGING_ERROR;
	}

	public static void setINCOMING_STATUS_MESSAGE_ERROR(String iNCOMING_STATUS_MESSAGE_ERROR) {
		INCOMING_STATUS_MESSAGE_ERROR = iNCOMING_STATUS_MESSAGE_ERROR;
	}

	public static void setINCOMING_STATUSD_MESSAGE(String iNCOMING_STATUSD_MESSAGE) {
		INCOMING_STATUSD_MESSAGE = iNCOMING_STATUSD_MESSAGE;
	}

	public static void setALERT_MESSAGE(String aLERT_MESSAGE) {
		ALERT_MESSAGE = aLERT_MESSAGE;
	}

	public static void setRESEND_MESSAGE(String rESEND_MESSAGE) {
		RESEND_MESSAGE = rESEND_MESSAGE;
	}

	public static void setREWORK_STATUS_MESSAGE(String rEWORK_STATUS_MESSAGE) {
		REWORK_STATUS_MESSAGE = rEWORK_STATUS_MESSAGE;
	}

	public static void setREMINDER_EMAIL(String rEMINDER_EMAIL) {
		REMINDER_EMAIL = rEMINDER_EMAIL;
	}

	public static void setINSERT_REPORT_ERROR(String iNSERT_REPORT_ERROR) {
		INSERT_REPORT_ERROR = iNSERT_REPORT_ERROR;
	}

	public static void setUPDATE_REPORT_ERROR(String uPDATE_REPORT_ERROR) {
		UPDATE_REPORT_ERROR = uPDATE_REPORT_ERROR;
	}

	public static void setNOTIFY_REMINDER_NOT_CONCLUDED_NR(String nOTIFY_REMINDER_NOT_CONCLUDED_NR) {
		NOTIFY_REMINDER_NOT_CONCLUDED_NR = nOTIFY_REMINDER_NOT_CONCLUDED_NR;
	}

	public static void setUPDATE_NOTES(String uPDATE_NOTES) {
		UPDATE_NOTES = uPDATE_NOTES;
	}

	public static void setREWORK_MESSAGE(String rEWORK_MESSAGE) {
		REWORK_MESSAGE = rEWORK_MESSAGE;
	}

	public static void setINCOMING_MESSAGE(String iNCOMING_MESSAGE) {
		INCOMING_MESSAGE = iNCOMING_MESSAGE;
	}

	public static void setINCOMING_MESSAGE_BUSINESS_XML_NOT_VALID_AND_SEND_STATUS_MESSAGE(
			String iNCOMING_MESSAGE_BUSINESS_XML_NOT_VALID_AND_SEND_STATUS_MESSAGE) {
		INCOMING_MESSAGE_BUSINESS_XML_NOT_VALID_AND_SEND_STATUS_MESSAGE = iNCOMING_MESSAGE_BUSINESS_XML_NOT_VALID_AND_SEND_STATUS_MESSAGE;
	}

	public static void setINCOMING_MESSAGE_BUSINESS_WITH_STATUS_MESSAGE_SUSPENDED(
			String iNCOMING_MESSAGE_BUSINESS_WITH_STATUS_MESSAGE_SUSPENDED) {
		INCOMING_MESSAGE_BUSINESS_WITH_STATUS_MESSAGE_SUSPENDED = iNCOMING_MESSAGE_BUSINESS_WITH_STATUS_MESSAGE_SUSPENDED;
	}

	public static void setINCOMING_MESSAGE_BUSINESS_AND_SEND_STATUS_MESSAGE(
			String iNCOMING_MESSAGE_BUSINESS_AND_SEND_STATUS_MESSAGE) {
		INCOMING_MESSAGE_BUSINESS_AND_SEND_STATUS_MESSAGE = iNCOMING_MESSAGE_BUSINESS_AND_SEND_STATUS_MESSAGE;
	}

	public static void setSEND_RESEND_STATUS_MESSAGE(String sEND_RESEND_STATUS_MESSAGE) {
		SEND_RESEND_STATUS_MESSAGE = sEND_RESEND_STATUS_MESSAGE;
	}

	public static void setALERT_STATUS_MESSAGE(String aLERT_STATUS_MESSAGE) {
		ALERT_STATUS_MESSAGE = aLERT_STATUS_MESSAGE;
	}

	public static void setINCOMING_MESSAGE_BUSINESS_FAILED_DECRYPTION(
			String iNCOMING_MESSAGE_BUSINESS_FAILED_DECRYPTION) {
		INCOMING_MESSAGE_BUSINESS_FAILED_DECRYPTION = iNCOMING_MESSAGE_BUSINESS_FAILED_DECRYPTION;
	}

	public static void setNOTIFY_REMINDER_NOT_CONCLUDED_RES(String nOTIFY_REMINDER_NOT_CONCLUDED_RES) {
		NOTIFY_REMINDER_NOT_CONCLUDED_RES = nOTIFY_REMINDER_NOT_CONCLUDED_RES;
	}

	public static void setSTART_BUILDING_MESSAGES_EXPIRED_FY(String sTART_BUILDING_MESSAGES_EXPIRED_FY) {
		START_BUILDING_MESSAGES_EXPIRED_FY = sTART_BUILDING_MESSAGES_EXPIRED_FY;
	}

	public static void setSTART_BUILDING_MESSAGES_SPECIFIC_COM(String sTART_BUILDING_MESSAGES_SPECIFIC_COM) {
		START_BUILDING_MESSAGES_SPECIFIC_COM = sTART_BUILDING_MESSAGES_SPECIFIC_COM;
	}

	public static void setSTART_BUILDING_MESSAGES_SPECIFIC_COUNTRY(String sTART_BUILDING_MESSAGES_SPECIFIC_COUNTRY) {
		START_BUILDING_MESSAGES_SPECIFIC_COUNTRY = sTART_BUILDING_MESSAGES_SPECIFIC_COUNTRY;
	}

	public static void setCURRENT_COUNTRY(String cURRENT_COUNTRY) {
		CURRENT_COUNTRY = cURRENT_COUNTRY;
	}

	public static void setCONTINUE_BUILDING_MESSAGE(String cONTINUE_BUILDING_MESSAGE) {
		CONTINUE_BUILDING_MESSAGE = cONTINUE_BUILDING_MESSAGE;
	}

	public static void setNEXT_COMMUNICATION(String nEXT_COMMUNICATION) {
		NEXT_COMMUNICATION = nEXT_COMMUNICATION;
	}

	public static void setSTART_NEW_MESSAGE(String sTART_NEW_MESSAGE) {
		START_NEW_MESSAGE = sTART_NEW_MESSAGE;
	}

	public static void setDATA_BUILDING_YEAR(String dATA_BUILDING_YEAR) {
		DATA_BUILDING_YEAR = dATA_BUILDING_YEAR;
	}

	public static String CURRENT_COUNTRY;

	public static String CONTINUE_BUILDING_MESSAGE;

	public static String NEXT_COMMUNICATION;

	public static String START_NEW_MESSAGE;

	public static String DATA_BUILDING_YEAR;

	public static void setPROCESS_HISTORY(String pROCESS_HISTORY) {
		PROCESS_HISTORY = pROCESS_HISTORY;
	}

	public static void setUPDATE_STATUS(String uPDATE_STATUS) {
		UPDATE_STATUS = uPDATE_STATUS;
	}

	public static void setDELETE_COMMUNICATION(String dELETE_COMMUNICATION) {
		DELETE_COMMUNICATION = dELETE_COMMUNICATION;
	}

	public static void setEXPIRED_FISCAL_YEAR(String eXPIRED_FISCAL_YEAR) {
		EXPIRED_FISCAL_YEAR = eXPIRED_FISCAL_YEAR;
	}

	public static void setUPDATE_FISCAL_YEAR(String uPDATE_FISCAL_YEAR) {
		UPDATE_FISCAL_YEAR = uPDATE_FISCAL_YEAR;
	}

	public static void setBUILD_MESSAGE(String bUILD_MESSAGE) {
		BUILD_MESSAGE = bUILD_MESSAGE;
	}

	public static void setUPDATE_EFFECTIVE_DEST(String uPDATE_EFFECTIVE_DEST) {
		UPDATE_EFFECTIVE_DEST = uPDATE_EFFECTIVE_DEST;
	}

	public static void setFINALIZE_COMMUNICATION(String fINALIZE_COMMUNICATION) {
		FINALIZE_COMMUNICATION = fINALIZE_COMMUNICATION;
	}

	public static void setADD_EFFECTIVE_DEST(String aDD_EFFECTIVE_DEST) {
		ADD_EFFECTIVE_DEST = aDD_EFFECTIVE_DEST;
	}

	public static void setREMOVE_EFFECTIVE_DEST(String rEMOVE_EFFECTIVE_DEST) {
		REMOVE_EFFECTIVE_DEST = rEMOVE_EFFECTIVE_DEST;
	}

	public static void setLATE_COMMUNICATION(String lATE_COMMUNICATION) {
		LATE_COMMUNICATION = lATE_COMMUNICATION;
	}

	public static void setFINISHED_EXPIRED_COMMUNICATIONS(String fINISHED_EXPIRED_COMMUNICATIONS) {
		FINISHED_EXPIRED_COMMUNICATIONS = fINISHED_EXPIRED_COMMUNICATIONS;
	}

	public static void setAddContributeToEffectiveDest(String addContributeToEffectiveDest) {
		ADD_CONTRIBUTE_TO_EFFECTIVE_DEST = addContributeToEffectiveDest;
	}

	public static void setStartExcelDac7National(String startExcelDac7National) {
		START_EXCEL_DAC7_NATIONAL = startExcelDac7National;
	}

}
