package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import eu.europa.ec.taxud.validation.ValidationError;
import org.w3c.dom.Element;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Set;
import java.util.HashSet;
import java.util.ArrayList;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import org.apache.commons.lang3.StringUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import oecd.ties.dpistf.v1.OECDDocTypeIndicEnumType;

dialect "java"

rule "TR-80011"
auto-focus true
	
when
	$element : Element("DPIBody" == getLocalName())
    $context : ValidationContext()
    $xpath   : XPath() from $context.getProperty("XPATH")
then
	HashSet<String> corrDocRefIdsFromContext = (HashSet<String>)$context.getProperty("RULE_80011_REF_IDS");

    final List<Element> docRefIds = XmlUtils.findElements($context, $element, "dpi:PlatformOperator/dpi:DocSpec");
    docRefIds.addAll(XmlUtils.findElements($context, $element, "dpi:OtherPlatformOperators/dpi:AssumedPlatformOperator/dpi:DocSpec"));
    docRefIds.addAll(XmlUtils.findElements($context, $element, "dpi:ReportableSeller/dpi:DocSpec"));

    for (final Element elem : docRefIds){
        String docTypeIndic = (String) XmlUtils.getChildObjectValue($context, elem, "stf:DocTypeIndic", XPathConstants.STRING);
        if(OECDDocTypeIndicEnumType.OECD_2.value().equals(docTypeIndic) ||OECDDocTypeIndicEnumType.OECD_3.value()
        .equals(docTypeIndic) ) {
            String corrDocRefId = (String) XmlUtils.getChildObjectValue($context, elem, "stf:CorrDocRefId", XPathConstants.STRING);
            if (corrDocRefIdsFromContext == null){
                    corrDocRefIdsFromContext = new HashSet<>();
                    corrDocRefIdsFromContext.add(corrDocRefId);
                    $context.setProperty("RULE_80011_REF_IDS", corrDocRefIdsFromContext);
                }else {
                    boolean added = corrDocRefIdsFromContext.add(corrDocRefId);
                    if (!added){
                        String docRefId = (String) XmlUtils.getChildObjectValue($context, elem, "stf:DocRefId", XPathConstants.STRING);
                        addError($context, ErrorCode.BR_TR_80011, docRefId, elem);
                    }
                }
            }
        }
end
