package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import eu.europa.ec.taxud.validation.ValidationError;
import org.w3c.dom.Element;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Set;
import java.util.HashSet;
import java.util.ArrayList;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import org.apache.commons.lang3.StringUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import oecd.ties.dpistf.v1.OECDDocTypeIndicEnumType
import eu.europa.ec.taxud.dac7.utils.RuleUtils
import eu.europa.ec.taxud.dac7.validation.Constants
import oecd.ties.dpi.v1.DPIMessageTypeIndicEnumType;

dialect "java"

rule "TR-90030"
auto-focus true
	
when
	$element : Element("DPIBody" == getLocalName())
    $context : ValidationContext()
    $xpath   : XPath() from $context.getProperty("XPATH")
then
    final List<Element> docTypeIndics = XmlUtils.findElements($context, $element, "dpi:PlatformOperator/dpi:DocSpec/stf:DocTypeIndic");
    docTypeIndics.addAll(XmlUtils.findElements($context, $element, "dpi:OtherPlatformOperators/dpi:AssumedPlatformOperator/dpi:DocSpec/stf:DocTypeIndic"));
    docTypeIndics.addAll(XmlUtils.findElements($context, $element, "dpi:ReportableSeller/dpi:DocSpec/stf:DocTypeIndic"));
    boolean containsOnlyResentData = true;

    for (final Element elem : docTypeIndics) {
        if(!OECDDocTypeIndicEnumType.OECD_0.value().equals(elem.getTextContent())) {
            containsOnlyResentData = false;
            break;
        }
    }

    if (containsOnlyResentData){
        addErrorWithoutRefId($context, ErrorCode.BR_TR_90030, $element);
    }
end
