package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import eu.europa.ec.taxud.validation.ValidationError;
import eu.europa.ec.taxud.dac7.validation.Constants;
import eu.europa.ec.taxud.dac7.validation.ErrorCode;
import eu.europa.ec.taxud.dac7.utils.ValidationContextUtils;
import eu.europa.ec.taxud.dac7.utils.XmlUtils;
import org.apache.commons.lang3.StringUtils;
import org.w3c.dom.Element;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;

dialect "java"

rule "No-Status-Message"
	when
        $element : Element("MessageSpec" == getLocalName() && "urn:oecd:ties:dsm:v1" != getNamespaceURI())
    then
end
