package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import org.w3c.dom.Element;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import eu.europa.ec.taxud.dac7.validation.Constants
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import java.util.Date
import java.util.Calendar
import java.text.SimpleDateFormat;
import org.w3c.dom.Node
import eu.europa.ec.taxud.dac7.utils.RuleUtils
import java.util.Set
import java.util.HashSet
import oecd.ties.isodpitypes.v1.MSCountryCodeType;

dialect "java"

rule "TR-30030"
extends "DAC7-DPI-BODY"
agenda-group "DAC7-DPI-BODY"
auto-focus true

	when
        $elementRS : Element() from XmlUtils.findElements($context, $element, "//dpi:ReportableSeller/dpi:Identity/dpi:EntitySeller/dpi:GVS")
        or
        $elementRS : Element() from XmlUtils.findElements($context, $element, "//dpi:ReportableSeller/dpi:Identity/dpi:IndividualSeller/dpi:GVS")
    then

        if($context.getProperty(Constants.EU_SPECIFIC_RULES) != null && !(Boolean)$context.getProperty(Constants.EU_SPECIFIC_RULES)){
            return;
        }

       if (RuleUtils.isParameterProvided($elementRS)){
           String docTypeIndic = (String) XmlUtils.getChildObjectValue($context, $element, "dpi:ReportableSeller/dpi:DocSpec/stf:DocRefId", XPathConstants.STRING);
           addError($context, ErrorCode.BR_RS_003, docTypeIndic, $element);
       }
end
