package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import org.w3c.dom.Element;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import eu.europa.ec.taxud.dac7.validation.Constants
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import java.util.Date
import java.util.Calendar
import java.text.SimpleDateFormat;

dialect "java"

rule "TR-40130"
extends "DAC7-DPI-BODY"
agenda-group "DAC7-DPI-BODY"
auto-focus true

	when
        $elementIS : Element() from XmlUtils.findElements($context, $element, "//dpi:ReportableSeller/dpi:Identity/dpi:IndividualSeller/dpi:Standard/dpi:IndSellerID")
    then
        Calendar calBirthDate = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(Constants.DATE_FORMAT);
        String birthDate = (String) XmlUtils.getChildObjectValue($context, $elementIS, "dpi:BirthInfo/dpi:BirthDate", XPathConstants.STRING);
        calBirthDate.setTime(sdf.parse(birthDate));
        int birthDateYear = calBirthDate.get(Calendar.YEAR);

        Calendar cal = Calendar.getInstance();
        int currentYear =  cal.get(Calendar.YEAR);
        if (birthDateYear < 1900 || birthDateYear > currentYear) {
            String docTypeIndic = (String) XmlUtils.getChildObjectValue($context, $element, "dpi:ReportableSeller/dpi:DocSpec/stf:DocRefId", XPathConstants.STRING);
            addError($context, ErrorCode.BR_PAR_014, docTypeIndic, $elementIS);
        }
end
