package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import eu.europa.ec.taxud.validation.ValidationError;
import org.w3c.dom.Element;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Set;
import java.util.HashSet;
import java.util.ArrayList;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import org.apache.commons.lang3.StringUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import eu.europa.ec.taxud.dac7.validation.Constants
import oecd.ties.dpi.v1.DPIMessageTypeIndicEnumType
import eu.europa.ec.taxud.dac7.utils.RuleUtils

dialect "java"

rule "TR-80006"
auto-focus true
	
when
	$element : Element("DPIBody" == getLocalName())
    $context : ValidationContext()
    $xpath   : XPath() from $context.getProperty("XPATH")
then
    final List<Element> docSpecs = XmlUtils.findElements($context, $element, "dpi:PlatformOperator/dpi:DocSpec/stf:CorrMessageRefId");
    docSpecs.addAll(XmlUtils.findElements($context, $element, "dpi:OtherPlatformOperators/dpi:AssumedPlatformOperator/dpi:DocSpec/stf:CorrMessageRefId"));
    docSpecs.addAll(XmlUtils.findElements($context, $element, "dpi:ReportableSeller/dpi:DocSpec/stf:CorrMessageRefId"));

    for (final Element elem : docSpecs){
        if (RuleUtils.isParameterProvided(elem.getTextContent())){
            String docTypeIndic = (String) XmlUtils.getChildObjectValue($context, $element, "dpi:PlatformOperator/dpi:DocSpec/stf:DocRefId", XPathConstants.STRING);
            addError($context, ErrorCode.BR_TR_80006, docTypeIndic, elem);
        }
    }

end
