package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import eu.europa.ec.taxud.validation.ValidationError;
import org.w3c.dom.Element;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Set;
import java.util.HashSet;
import java.util.ArrayList;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import org.apache.commons.lang3.StringUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils;

dialect "java"

rule "TR-80000"
auto-focus true

when
	$element : Element("DPIBody" == getLocalName())
    $context : ValidationContext()
    $xpath   : XPath() from $context.getProperty("XPATH")
then
	HashSet<String> docRefIdsFromContext = (HashSet<String>)$context.getProperty("RULE_80001_REF_IDS");

    final List<Element> docRefIds = XmlUtils.findElements($context, $element, "dpi:PlatformOperator/dpi:DocSpec/stf:DocRefId");
    docRefIds.addAll(XmlUtils.findElements($context, $element, "dpi:OtherPlatformOperators/dpi:AssumedPlatformOperator/dpi:DocSpec/stf:DocRefId"));
    docRefIds.addAll(XmlUtils.findElements($context, $element, "dpi:ReportableSeller/dpi:DocSpec/stf:DocRefId"));

    for (final Element elem : docRefIds){
        if (docRefIdsFromContext == null){
            docRefIdsFromContext = new HashSet<>();
            docRefIdsFromContext.add(elem.getTextContent());
            $context.setProperty("RULE_80001_REF_IDS", docRefIdsFromContext);
        }else {
            boolean added = docRefIdsFromContext.add(elem.getTextContent());
            if (!added){
                addErrorWithoutRefId($context, ErrorCode.BR_TR_80000, elem);
            }
        }
    }

end
