package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import org.w3c.dom.Element;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import eu.europa.ec.taxud.dac7.validation.Constants
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode;

dialect "java"

rule "TR-40010"
extends "DAC7-DPI-BODY"
agenda-group "DAC7-DPI-BODY"
auto-focus true

	when
        $elementIS : Element() from XmlUtils.findElements($context, $element, "//dpi:ReportableSeller/dpi:Identity/dpi:IndividualSeller/dpi:Standard/dpi:IndSellerID")
    then
        List<Element> nationalities = XmlUtils.findElements($context, $elementIS, "dpi:Nationality");
        if (!nationalities.isEmpty()) {
            String docTypeIndic = (String) XmlUtils.getChildObjectValue($context, $element, "dpi:ReportableSeller/dpi:DocSpec/stf:DocRefId", XPathConstants.STRING);
            addError($context, ErrorCode.BR_PAR_001, docTypeIndic, $elementIS);
        }
end
