package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import org.w3c.dom.Element;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import eu.europa.ec.taxud.dac7.validation.Constants
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import oecd.ties.dpi.v1.INTypeEnumType
import eu.europa.ec.taxud.dac7.utils.RuleUtils;

dialect "java"

rule "TR-40110-OPO"
extends "DAC7-OTHER-PLATFORM-OPERATOR"
agenda-group "DAC7-OTHER-PLATFORM-OPERATOR"
auto-focus true

	when
    then
        List<Element> tins = XmlUtils.findElements($context, $otherPlatformOperator, "dpi:AssumedPlatformOperator/dpi:TIN");

        for (final Element elem : tins) {
            if (!RuleUtils.isParameterProvided(elem.getTextContent())){
                String unKnown = (String) XmlUtils.getChildObjectValue($context, elem, "./@unknown", XPathConstants.STRING);
                if (!RuleUtils.isParameterProvided(unKnown) || !Boolean.TRUE.equals(Boolean.valueOf(unKnown))) {
                    String docTypeIndic = (String) XmlUtils.getChildObjectValue($context, $otherPlatformOperator, "dpi:AssumedPlatformOperator/dpi:DocSpec/stf:DocRefId", XPathConstants.STRING);
                    addError($context, ErrorCode.BR_PAR_012, docTypeIndic, elem);
                }
            }
        }
end

rule "TR-40110-RS"
extends "DAC7-REPORTABLE-SELLER"
agenda-group "DAC7-REPORTABLE-SELLER"
auto-focus true

	when
	    $elemRS : Element() from XmlUtils.findElements($context, $reportableSeller, "//dpi:Identity/dpi:IndividualSeller/dpi:Standard/dpi:IndSellerID")
	    or
	    $elemRS : Element() from XmlUtils.findElements($context, $reportableSeller, "//dpi:Identity/dpi:EntitySeller/dpi:Standard/dpi:EntSellerID")
    then
        List<Element> tins = XmlUtils.findElements($context, $elemRS, "dpi:TIN");

        for (final Element elem : tins) {
            if (!RuleUtils.isParameterProvided(elem.getTextContent())){
                String unKnown = (String) XmlUtils.getChildObjectValue($context, elem, "./@unknown", XPathConstants.STRING);
                if (!RuleUtils.isParameterProvided(unKnown) || !Boolean.TRUE.equals(Boolean.valueOf(unKnown))) {
                    String docTypeIndic = (String) XmlUtils.getChildObjectValue($context, $reportableSeller, "dpi:DocSpec/stf:DocRefId", XPathConstants.STRING);
                    addError($context, ErrorCode.BR_PAR_012, docTypeIndic, elem);
                }
            }
        }
end

rule "TR-40110-PO"
extends "DAC7-PLATFORM-OPERATOR"
agenda-group "DAC7-PLATFORM-OPERATOR"
auto-focus true

	when
    then
        List<Element> tins = XmlUtils.findElements($context, $platformOperator, "dpi:TIN");

        for (final Element elem : tins) {
            if (!RuleUtils.isParameterProvided(elem.getTextContent())){
                String unKnown = (String) XmlUtils.getChildObjectValue($context, elem, "./@unknown", XPathConstants.STRING);
                if (!RuleUtils.isParameterProvided(unKnown) || !Boolean.TRUE.equals(Boolean.valueOf(unKnown))) {
                    String docTypeIndic = (String) XmlUtils.getChildObjectValue($context, $platformOperator, "dpi:DocSpec/stf:DocRefId", XPathConstants.STRING);
                    addError($context, ErrorCode.BR_PAR_012, docTypeIndic, elem);
                }
            }
        }
end
