package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import eu.europa.ec.taxud.validation.ValidationError;
import eu.europa.ec.taxud.dac7.utils.XmlUtils;
import eu.europa.ec.taxud.dac7.validation.ErrorCode;
import org.w3c.dom.Element;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import org.apache.commons.lang3.StringUtils;
import eu.europa.ec.taxud.dac7.validation.Constants
import eu.europa.ec.taxud.dac7.utils.DroolsUtils
import java.util.List
import java.util.Set
import java.lang.String
import java.util.HashSet;

dialect "java"

rule "TR-50012"
extends "DAC7-MessageSpecs"
agenda-group "DAC7-MessageSpecs"
auto-focus true

when
    $inputRR : String() from $context.getProperty(Constants.INPUT_RR);
then
	List<Element> countries = XmlUtils.findElements($context, $element, "dpi:ReceivingCountry");
	final Set<String> set = DroolsUtils.elementsToSet(countries);
	if(!set.contains($inputRR)){
	    addErrorWithoutRefId($context, ErrorCode.BR_MSG_002, $element);
	}
end
