package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import eu.europa.ec.taxud.validation.ValidationError;
import org.w3c.dom.Element;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Set;
import java.util.HashSet;
import java.util.ArrayList;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import org.apache.commons.lang3.StringUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import eu.europa.ec.taxud.dac7.validation.Constants
import oecd.ties.dpi.v1.DPIMessageTypeIndicEnumType

import eu.europa.ec.taxud.dac7.utils.RuleUtils
import oecd.ties.dpistf.v1.OECDDocTypeIndicEnumType
import java.util.Arrays
import org.w3c.dom.NodeList
import java.lang.annotation.ElementType

dialect "java"

rule "TR-80009"
auto-focus true
	
when
	$element : Element("DPIBody" == getLocalName())
    $context : ValidationContext()
    $xpath   : XPath() from $context.getProperty("XPATH")
then
    if (OECDDocTypeIndicEnumType.OECD_3.value()
        .equals(XmlUtils.getChildObjectValue($context, $element, "dpi:PlatformOperator/dpi:DocSpec/stf:DocTypeIndic", XPathConstants.STRING))){
        final List<Element> docTypeIndics = XmlUtils.findElements($context, $element, "dpi:OtherPlatformOperators/dpi:AssumedPlatformOperator/dpi:DocSpec/stf:DocTypeIndic");
        docTypeIndics.addAll(XmlUtils.findElements($context, $element, "dpi:ReportableSeller/dpi:DocSpec/stf:DocTypeIndic"));
        if (docTypeIndics.size() == 0 || docTypeIndics.stream().anyMatch(elem -> !OECDDocTypeIndicEnumType.OECD_3.value().equals(elem.getTextContent()))) {
             addErrorWithoutRefId($context, ErrorCode.BR_TR_80009, $element);
        }
    }

end
