package ec.dgtaxud.dac.val

import eu.europa.ec.taxud.validation.ValidationContext;
import eu.europa.ec.taxud.validation.ValidationError;
import org.w3c.dom.Element;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Set;
import java.util.HashSet;
import java.util.ArrayList;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants
import org.apache.commons.lang3.StringUtils
import eu.europa.ec.taxud.dac7.validation.ErrorCode
import java.util.List
import eu.europa.ec.taxud.dac7.utils.XmlUtils
import eu.europa.ec.taxud.dac7.validation.Constants;

dialect "java"

rule "TR-80001"
auto-focus true
	
when
	$element : Element("DPIBody" == getLocalName())
    $context : ValidationContext()
    $xpath   : XPath() from $context.getProperty("XPATH")
then
    final List<Element> docRefIds = XmlUtils.findElements($context, $element, "dpi:PlatformOperator/dpi:DocSpec/stf:DocRefId");
    docRefIds.addAll(XmlUtils.findElements($context, $element, "dpi:OtherPlatformOperators/dpi:AssumedPlatformOperator/dpi:DocSpec/stf:DocRefId"));
    docRefIds.addAll(XmlUtils.findElements($context, $element, "dpi:ReportableSeller/dpi:DocSpec/stf:DocRefId"));

    for (final Element elem : docRefIds) {
        String pattern = "(\\w{2})(\\d{4}).*";
        Pattern r = Pattern.compile(pattern);
        Matcher matcher = r.matcher(elem.getTextContent());
        if (matcher.matches()){
            final String transmittingCountry = (String) $context.getProperty(Constants.TRANSMITTING_COUNTRY);
            final String reportingPeriod = (String) $context.getProperty(Constants.REPORTING_PERIOD);
            final String reportingPeriodYear = reportingPeriod.substring(0, 4);
            final String sender = matcher.group(1);
            final String year = matcher.group(2);
            if (!sender.equals(transmittingCountry) || !reportingPeriodYear.equals(year)) {
                addErrorWithoutRefId($context, ErrorCode.BR_TR_80001, elem);
            }
        } else {
            addErrorWithoutRefId($context, ErrorCode.BR_TR_80001, elem);
        }
    }

end
